name: Secret Debugger
on: [push]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secrets
        run: |
          if [ -n "${{ secrets.REMOTE_HOST }}" ]; then echo "Host secret is set"; else echo "Host secret is EMPTY"; fi
          if [ -n "${{ secrets.REMOTE_USER }}" ]; then echo "User secret is set"; else echo "User secret is EMPTY"; fi
